import os
v = input("版本号:")
os.system("mkdir .\\Release\\"+v)
os.system("copy .\\GCHZ.c .\\Release\\"+v+"\\")
os.system(f"windres GCmain.rc GCmain.o")
os.system(f"gcc GCHZ.c GCmain.o -o {v}_Orgin.exe")
os.system(f"move GCmain.o .\\Release\\{v}\\")
os.system(f"move {v}_Orgin.exe .\\Release\\{v}\\")
os.system(f"upx --best .\\Release\\{v}\\{v}_Orgin.exe -o .\\Release\\{v}\\lxKMS{v}.exe")
os.system(f"gcc -S .\\Release\\{v}\\GCHZ.c -o .\\Release\\{v}\\GCHZ.asm")
os.system(f"mkdir .\\Pubverc\\{v}\\")
os.system(f"copy .\\Release\\{v}\\lxKMS{v}.exe .\\Pubverc\\{v}\\")
os.system(f"xcopy .\\Pubverc E:\\AutoKMS\\ /e /s /y")
os.system(f"xcopy .\\Pubverc\\{v} E:\\AutoKMS\\{v}\\ /e /s /y")
input('')
print("Done")
#input("")
